{{- if .Values.ssh.authorizedKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bastion.fullname" . }}-ssh-keys
  labels:
    {{- include "bastion.labels" . | nindent 4 }}
type: Opaque
data:
  authorized_keys: {{ (join "\n" .Values.ssh.authorizedKeys) | b64enc | quote }}
{{- else if .Values.ssh.authorizedKeysSecret }}
{{- /* Secret will be referenced from existing secret */}}
{{- end }}

