{{- $name := include "x-road-ssx.fullnameWithId" . -}}
{{- $ns := .Release.Namespace -}}
{{- $secret := lookup "v1" "Secret" $ns $name -}}
# Security Server application secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "x-road-ssx.labels" . | nindent 4 }}
{{- if $secret }}
data:
  tokenPin: {{ $secret.data.tokenPin }}
  password: {{ $secret.data.password }}
{{- else }}
stringData:
  tokenPin: {{ printf "%s%s%s%s" (randAlpha 3 | upper) (randAlpha 3 | lower) (randNumeric 3) "#!" | quote }}
  password: {{ randAlphaNum 32 | quote }}
{{- end }}
---
# Secret for X-Road SS certificates
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "x-road-ssx.fullnameWithId" . }}-cert
  labels:
    {{- include "x-road-ssx.labels" . | nindent 4 }}
type: Opaque
data:
  # These will be populated from external files
  certificate.crt: {{ .Files.Get "certs/certificate-ss.crt" | required "certificate-ss.crt file is required in certs/ directory" | b64enc }}
  certificate.key: {{ .Files.Get "certs/certificate-ss.key" | required "certificate-ss.key file is required in certs/ directory" | b64enc }}
  certificate-ss-ui.p12: {{ .Files.Get "certs/certificate-ss-ui.p12" | required "certificate-ss-ui.p12 file is required in certs/ directory" | b64enc }}
  certificate-ss-internal.p12: {{ .Files.Get "certs/certificate-ss-internal.p12" | required "certificate-ss-internal.p12 file is required in certs/ directory" | b64enc }}
---
# CA
{{- $ns := .Release.Namespace -}}
{{- $secret := lookup "v1" "Secret" $ns "test-ca-trust" -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: test-ca-trust
  labels:
    {{- include "x-road-ssx.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.pem: |
{{ .Files.Get "certs/ca.pem" | indent 4 }}
{{- end }}