{{- $name := include "x-road-ss.fullnameWithId" . -}}
{{- $ns := .Release.Namespace -}}
{{- $secret := lookup "v1" "Secret" $ns $name -}}
# TODO sass
# Security Server application secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "x-road-ss.labels" . | nindent 4 }}
{{- if $secret }}
data:
  tokenPin: {{ $secret.data.tokenPin }}
  password: {{ $secret.data.password }}
{{- else }}
stringData:
  tokenPin: {{ printf "%s%s%s%s" (randAlpha 3 | upper) (randAlpha 3 | lower) (randNumeric 3) "#!" | quote }}
  password: {{ randAlphaNum 32 | quote }}
{{- end }}
---
# Secret for X-Road SS certificates
# Note: Certificates are created via SS UI during configuration, not at installation time
# This secret is only created if certificate files exist in the certs/ directory
{{- if .Files.Get "certs/certificate-ss.crt" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "x-road-ss.fullnameWithId" . }}-cert
  labels:
    {{- include "x-road-ss.labels" . | nindent 4 }}
type: Opaque
data:
  # These will be populated from external files if they exist
  certificate-ss.crt: {{ .Files.Get "certs/certificate-ss.crt" | b64enc }}
  certificate-ss.key: {{ .Files.Get "certs/certificate-ss.key" | b64enc }}
  certificate-ss-ui.p12: {{ .Files.Get "certs/certificate-ss-ui.p12" | b64enc }}
  certificate-ss-internal.p12: {{ .Files.Get "certs/certificate-ss-internal.p12" | b64enc }}
  # Also include as certificate.crt/key for compatibility
  certificate.crt: {{ .Files.Get "certs/certificate-ss.crt" | b64enc }}
  certificate.key: {{ .Files.Get "certs/certificate-ss.key" | b64enc }}
{{- end }}
---
# CA Trust Secret
# Note: CA certificate is embedded in values.yaml for standalone distribution
# If certs/ca.pem exists, use it; otherwise use embedded value from values.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-ca-trust
  labels:
    {{- include "x-road-ss.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.pem: |
{{- if .Files.Get "certs/ca.pem" }}
{{ .Files.Get "certs/ca.pem" | indent 4 }}
{{- else if hasKey .Values "caCerts" }}
{{ index .Values "caCerts" "ca.pem" | b64dec | indent 4 }}
{{- else }}
    # CA certificate not provided
    # Please provide certs/ca.pem or configure caCerts in values.yaml
{{- end }}
---
{{- if and (index .Values "security-server" "Ingress" "enabled") }}
# Self-signed certificate for Ingress TLS termination
# This certificate is used by the Ingress controller for HTTPS on port 443
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "x-road-ss.fullnameWithId" . }}-https-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "x-road-ss.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  # Self-signed certificate and key for Ingress
  # Certificate files should be provided in certs/ingress-tls.crt and certs/ingress-tls.key
  # If not provided, a placeholder will be created (you'll need to generate the certificate separately)
  tls.crt: |
{{- if and (.Files.Get "certs/ingress-tls.crt") (.Files.Get "certs/ingress-tls.key") }}
{{ .Files.Get "certs/ingress-tls.crt" | indent 4 }}
{{- else }}
    # Self-signed certificate for {{ include "x-road-ss.ingressFqdn" . }} and {{ .Values.bbDomain | default "bb-im-second-cluster.assembly.govstack.global" }}
    # Generate using: openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    #   -keyout certs/ingress-tls.key -out certs/ingress-tls.crt \
    #   -subj "/CN={{ include "x-road-ss.ingressFqdn" . }}" \
    #   -addext "subjectAltName=DNS:{{ include "x-road-ss.ingressFqdn" . }},DNS:{{ .Values.bbDomain | default "bb-im-second-cluster.assembly.govstack.global" }}"
{{- end }}
  tls.key: |
{{- if and (.Files.Get "certs/ingress-tls.crt") (.Files.Get "certs/ingress-tls.key") }}
{{ .Files.Get "certs/ingress-tls.key" | indent 4 }}
{{- else }}
    # Private key for {{ include "x-road-ss.ingressFqdn" . }}
    # Generate using the command shown in tls.crt comment above
{{- end }}
{{- end }}


