{{- if and (index .Values "security-server" "persistence" "enabled") }}
{{- range $name, $cfg := index .Values "security-server" "persistence" }}
{{- if ne $name "enabled" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ include "x-road-ss.fullnameWithId" $ }}-{{ $name }}
  labels:
    {{- include "x-road-ss.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ $cfg.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ required (printf "security-server.persistence.%s.size is required" $name) $cfg.size }}
  {{- if hasKey $cfg "storageClassName" }}
  storageClassName: {{- if $cfg.storageClassName }} {{ $cfg.storageClassName | quote }} {{- else }} "" {{- end }}
  {{- end }}
  {{- with $cfg.bind }}
  {{- if .enabled }}
    {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
    {{- end }}
    {{- if or .matchLabels .matchExpressions }}
  selector:
      {{- if .matchLabels }}
    matchLabels:{{ toYaml .matchLabels | nindent 6 }}
      {{- end }}
      {{- if .matchExpressions }}
    matchExpressions:{{ toYaml .matchExpressions | nindent 6 }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "x-road-ss.fullnameWithId" $ }}
  labels:
    {{- include "x-road-ss.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "x-road-ss.fullnameWithId" $ }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "x-road-ss.fullnameWithId" $ }}
        {{- include "x-road-ss.labels" . | nindent 8 }}
    spec:
      containers:
{{ include "x-road-ss.container.main" . | indent 8 }}
      initContainers:
{{ include "x-road-ss.container.init.copyCerts" . | indent 8 }}
{{- /* CA installation init container commented out */ -}}
{{- if false }}
{{ include "x-road-ss.container.init.installCa" . | indent 8 }}
{{- end }}
      volumes:
        - name: xroad-config
          persistentVolumeClaim:
            claimName: pvc-{{ include "x-road-ss.fullnameWithId" $ }}-config
        - name: xroad-lib
          persistentVolumeClaim:
            claimName: pvc-{{ include "x-road-ss.fullnameWithId" $ }}-lib
        - name: xroad-dbdata
          persistentVolumeClaim:
            claimName: pvc-{{ include "x-road-ss.fullnameWithId" $ }}-dbdata
        {{- if .Files.Get "certs/certificate-ss.crt" }}
        - name: certs
          secret:
            secretName: {{ include "x-road-ss.fullnameWithId" $ }}-cert
        {{- end }}
        - name: test-ca-cert
          secret:
            secretName: test-ca-trust
        - name: shared-truststore
          emptyDir: {}
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "x-road-ss.fullnameWithId" $ }}
  labels:
    {{- include "x-road-ss.labels" . | nindent 4 }}
  {{- if (index .Values "security-server" "Service" "annotations") }}
  annotations:
    {{- toYaml (index .Values "security-server" "Service" "annotations") | nindent 4 }}
  {{- end }}
spec:
  type: {{ index .Values "security-server" "Service" "type" | default "LoadBalancer" }}
  selector:
    app: {{ include "x-road-ss.fullnameWithId" $ }}
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: admin-ui
      # Service port 4000 maps directly to pod port 4000
    - port: 5500
      targetPort: 5500
      protocol: TCP
      name: messaging
    - port: 5577
      targetPort: 5577
      protocol: TCP
      name: ocsp
    - port: 5588
      targetPort: 5588
      protocol: TCP
      name: proxy-ui
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: proxy-http
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: proxy-https
---
{{- if and (index .Values "security-server" "Ingress" "enabled") }}
# Ingress resources (nginx and traefik)
# Ingress route: External port 443 (HTTPS) → Backend port 4000 (SS Admin UI)
# TLS terminates at Ingress using self-signed certificate
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "x-road-ss.fullnameWithId" $ }}-https
  annotations:
    # TLS terminates at Ingress using self-signed certificate, proxy to HTTPS backend
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # Timeout settings
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    # Skip SSL verification for backend (since we're using self-signed certs)
    nginx.ingress.kubernetes.io/backend-protocol-verify: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ include "x-road-ss.ingressFqdn" $ }}
        - {{ .Values.bbDomain | default "bb-im-second-cluster.assembly.govstack.global" }}
      secretName: {{ include "x-road-ss.fullnameWithId" $ }}-https-tls
  rules:
    - host: {{ include "x-road-ss.ingressFqdn" $ }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "x-road-ss.fullnameWithId" $ }}
                port:
                  number: 4000  # External 443 → Backend 4000 (SS Admin UI)
    - host: {{ .Values.bbDomain | default "bb-im-second-cluster.assembly.govstack.global" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "x-road-ss.fullnameWithId" $ }}
                port:
                  number: 4000  # External 443 → Backend 4000 (SS Admin UI)
---
# X-Road Security Server Message Exchange LoadBalancer Service (BB-IM)
# Exposes port 5500 (message exchange) via MetalLB
# CRITICAL: This port is used for inter-Security Server communication
# NOTE: BB-IM hosts BOTH Central Server AND Security Server (dual role)
apiVersion: v1
kind: Service
metadata:
  name: xroad-ss-messaging-lb
  namespace: im-ns
  labels:
    app.kubernetes.io/name: xroad-security-server
    app.kubernetes.io/component: security-server
    app.kubernetes.io/part-of: x-road-information-mediator
    govstack.im/port-type: message-exchange
    govstack.im/cluster-role: dual  # BB-IM hosts both CS and SS
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.100
    metallb.universe.tf/allow-shared-ip: "shared-vip"
    govstack.im/port-description: "X-Road Security Server message exchange (inter-server communication)"
    govstack.im/external-port: "5500"
    govstack.im/protocol-notes: "HTTPS protocol for X-Road message exchange"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: message-exchange
      protocol: TCP
      port: 5500
      targetPort: 5500
  selector:
    app.kubernetes.io/name: xroad-security-server
    app.kubernetes.io/component: security-server
---
# X-Road Security Server OCSP LoadBalancer Service (BB-IM)
# Exposes port 5577 (OCSP responses) via MetalLB
# CRITICAL: This port is used for certificate validation via OCSP protocol
# NOTE: BB-IM hosts BOTH Central Server AND Security Server (dual role)
apiVersion: v1
kind: Service
metadata:
  name: xroad-ss-ocsp-lb
  namespace: im-ns
  labels:
    app.kubernetes.io/name: xroad-security-server
    app.kubernetes.io/component: security-server
    app.kubernetes.io/part-of: x-road-information-mediator
    govstack.im/port-type: ocsp
    govstack.im/cluster-role: dual  # BB-IM hosts both CS and SS
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.100
    metallb.universe.tf/allow-shared-ip: "shared-vip"
    govstack.im/port-description: "X-Road Security Server OCSP responses (certificate validation)"
    govstack.im/external-port: "5577"
    govstack.im/protocol-notes: "HTTP protocol for OCSP certificate validation"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ocsp
      protocol: TCP
      port: 5577
      targetPort: 5577
  selector:
    app.kubernetes.io/name: xroad-security-server
    app.kubernetes.io/component: security-server
---
{{- if and (index .Values "security-server" "Ingress" "traefik" "enabled") }}
{{- include "x-road-ss.traefik.ingress" . }}
{{- end }}
{{- end }}
# End of Ingress resources block (closes if from line 126)
