{{- $name := include "x-road-csx.fullnameWithId" . -}}
{{- $ns := .Release.Namespace -}}
{{- $secret := lookup "v1" "Secret" $ns $name -}}
# Central Server application secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "x-road-csx.labels" . | nindent 4 }}
type: Opaque
{{- if $secret }}
data:
  dbPassword: {{ index $secret.data "dbPassword" }}
  tokenPin:   {{ index $secret.data "tokenPin" }}
  password:   {{ index $secret.data "password" }}
{{- else }}
stringData:
  dbPassword: {{ randAlphaNum 32 | quote }}
  tokenPin:   {{ printf "%s%s%s%s" (randAlpha 3 | upper) (randAlpha 3 | lower) (randNumeric 3) "#!" | quote }}
  password:   {{ randAlphaNum 32 | quote }}
{{- end }}
---
# Certificates
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "x-road-csx.fullnameWithId" $ }}-cert
  labels:
    {{- include "x-road-csx.labels" . | nindent 4 }}
#type: kubernetes.io/tls
type: Opaque
data:
  # These will be populated from external files
  certificate.crt: {{ .Files.Get "certs/certificate.crt" | required "certificate.crt file is required in certs/ directory" | b64enc }}
  certificate.key: {{ .Files.Get "certs/certificate.key" | required "certificate.key file is required in certs/ directory" | b64enc }}
  certificate-cs.p12: {{ .Files.Get "certs/certificate-cs.p12" | required "certificate-cs.p12 file is required in certs/ directory" | b64enc }}
---
# CA
{{- $ns := .Release.Namespace -}}
{{- $secret := lookup "v1" "Secret" $ns "test-ca-trust" -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: test-ca-trust
  labels:
    {{- include "x-road-csx.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.pem: |
{{ .Files.Get "certs/ca.pem" | indent 4 }}
{{- end }}
